// Server/FreelaAPI/Freela.Website/Freela_Website/src/app/components/page-header/page-header.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-page-header',
  templateUrl: './page-header.component.html',
  styleUrls: ['./page-header.component.css']
})
export class PageHeaderComponent implements OnInit {

  @Input() title : string = 'Page Header';
  constructor() { }

  ngOnInit(): void {
  }

}


<div class='page-header-component' >
  <header class="page-header">
    <div class="top-bar-container">
        <a >
            <img src="../../../assets/images/icons/back.svg" alt="" />
        </a>
        <img src="../../assets/images/icons/Freela.svg" alt="" />
    </div>

    <div class="header-content">
        <div class='title'>
            <h2>{{title}}</h2>
        </div>
    </div>
  </header>
</div>

// front-end/src/components/pageHeader/index.tsx
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom'
import backIcon from '../../assets/images/icons/back.svg'
import logoImg from '../../assets/images/icons/Freela.svg';
import './styles.css';

interface PageHeaderProps{
    title:string;
}

const PageHeader : React.FC<PageHeaderProps> = (props) => {

return(
    <div className='page-header-component' >
         <header className="page-header">
                    <div className="top-bar-container">
                        <Link to="/">
                            <img src={backIcon} alt="" />
                        </Link>
                        <img src={logoImg} alt="" />
                    </div>

                    <div className="header-content">
                        <div className='title'>
                            <h2>{props.title}</h2>
                        </div>
                    </div>
                </header>
    </div>
    )
}

export default PageHeader;
