// Server/FreelaAPI/Freela.Website/Freela_Website/src/app/Pages/freela-list/freela-list.component.ts
import { Component, OnInit } from '@angular/core';
import { Freela } from 'src/app/models/freela';

@Component({
  selector: 'app-freela-list',
  templateUrl: './freela-list.component.html',
  styleUrls: ['./freela-list.component.css']
})
export class FreelaListComponent implements OnInit {

  freelas : Freela[] = [];
  freela : Freela = {
    Id : 1,
    Name : 'Marco Polo' ,
    Whatsapp :'544645' ,
    PhotoURL : 'dfdsfsd',
    Biography : 'Lorem ipsum dolor sit amet, consectetur, sed do eiusmod tempor incididunt ut labore et dol' ,
    Area : 'Design',
    Price : '20',
    Curriculum :'asdasdasd',
    Company : {
      CompanyRanking: 3
    }
  }


  constructor() { }

  ngOnInit(): void {
    this.freelas.push(this.freela)
    this.freelas.push(this.freela)
    this.freelas.push(this.freela)
    this.freelas.push(this.freela)
    this.freelas.push(this.freela)
    this.freelas.push(this.freela)
    this.freelas.push(this.freela)
    this.freelas.push(this.freela)
    this.freelas.push(this.freela)
  }

}


<div id="page-freela-list">
    <div id="freela-list" class="container">
      <app-page-header title="Estes são os Freelas disponíveis."></app-page-header>
        <div class="form-container">
            <form id="search-freelas" class="container">
                <div class="input-block">
                    <label htmlFor="subject">Area</label>
                    <input type="text" id="subject" />
                </div>

                <div class="input-block">
                    <label htmlFor="hour">Valor Hora</label>
                    <input type="text" id="hour" />
                </div>

                <div class="input-block">
                    <label htmlFor="time">Dias disponíveis</label>
                    <input type="text" id="time" />
                </div>
            </form>
        </div>
    </div>
    <div class="page-content">
      <div class="list">
        <div *ngFor="let fre123 of freelas" >
          <app-freela-item  [freela]="fre123"></app-freela-item>
        </div>
      </div>
    </div>
</div>

// front-end/src/pages/FreelaList/index.jsx
import React from "react";
import Footer from "../../components/footer";
import { Link } from 'react-router-dom'
import backIcon from '../../assets/images/icons/back.svg'
import logoImg from '../../assets/images/icons/Freela.svg';
import PageHeader from "../../components/pageHeader";
import FreelaItem from "../../components/freelaItem";

import './styles.css';

function FreelaList(){
    return (
        <div id="page-freela-list">
            <div id="freela-list" className="container">
                <PageHeader title="Estes são os Freelas disponíveis."/>
                <div className="form-container">
                    <form id="search-freelas" className="container">
                        <div className="input-block">
                            <label htmlFor="subject">Area</label>
                            <input type="text" id="subject" />
                        </div>

                        <div className="input-block">
                            <label htmlFor="hour">Valor Hora</label>
                            <input type="text" id="hour" />
                        </div>

                        <div className="input-block">
                            <label htmlFor="time">Dias disponíveis</label>
                            <input type="text" id="time" />
                        </div>
                    </form>
                </div>
            </div>
            <div className="page-content">
                <div className="list">
                    <FreelaItem/>
                    <FreelaItem/>
                    <FreelaItem/>
                    <FreelaItem/>
                    <FreelaItem/>
                    <FreelaItem/>
                    <FreelaItem/>
                    <FreelaItem/>
                    <FreelaItem/>
                    <FreelaItem/>
                    <FreelaItem/>
                    <FreelaItem/>
                    <FreelaItem/>
                    <FreelaItem/>
                    <FreelaItem/>
                </div>
              
            </div>
            <Footer></Footer>
        </div>
    )
}
export default FreelaList;
