// Server/FreelaAPI/Freela.Website/Freela_Website/src/app/components/freela-item/freela-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Freela } from 'src/app/models/freela';

@Component({
  selector: 'app-freela-item',
  templateUrl: './freela-item.component.html',
  styleUrls: ['./freela-item.component.css']
})
export class FreelaItemComponent implements OnInit {

  @Input() freela?: Freela;

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="freela-item">
  <div class="container">
  <header>
      <img src="https://img.freepik.com/fotos-gratis/empresario-de-baixo-angulo_23-2148825893.jpg?w=1380&t=st=1666002190~exp=1666002790~hmac=0ea6c49f5bd6ef23faf3a3401f84a6b42efd3a5d3e11b01fd0f5ceb567cd9363" alt="" />
      <div class="header-content">
        <div style="width: 30rem;">
          <strong class='strong'>{{freela?.Name}}</strong>
          <span>{{freela?.Area}}</span>
          <freela-ranking [freelaRanking]="freela?.Company?.CompanyRanking" ></freela-ranking>
        </div>
        <div class="ver-perfil">
          Ver perfil
        </div>
      </div>
  </header>
  <div class="content">
    <p>{{freela?.Biography}} Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius non, adipisci voluptatem atque nam, hic voluptate necessitatibus vero ratione expedita impedit praesentium reiciendis quod ipsa inventore voluptatum, tempora distinctio libero? Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda doloribus blanditiis excepturi eveniet voluptates at sed odit natus, eaque error animi? Beatae saepe blanditiis fuga perspiciatis accusamus veritatis a Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis veniam dolore amet. Non unde quibusdam corrupti fugiat! Eius deserunt enim nemo in recusandae! Soluta corrupti dolorum cumque hic illum cupiditate!</p>
  </div>
</div>
  <footer>
      <p>Preço/hora
          <strong>R$ {{freela?.Price}},00</strong>
      </p>
      <button type="button">
          <img src="../../../assets/images/icons//whatsapp.svg" alt="" />
          Entrar em contato
      </button>
  </footer>
</div>

// front-end/src/components/freelaItem/index.tsx
import React, { useState, useEffect } from 'react';
import whatsappIcon from "../../assets/images/icons/whatsapp.svg"
import './styles.css';


function FreelaItem() {

return(
    <div className="freela-item">
    <header>
        <img src="https://img.freepik.com/fotos-gratis/empresario-de-baixo-angulo_23-2148825893.jpg?w=1380&t=st=1666002190~exp=1666002790~hmac=0ea6c49f5bd6ef23faf3a3401f84a6b42efd3a5d3e11b01fd0f5ceb567cd9363" alt="" />
            <div>
                <strong>Mauro Dias</strong>
                <span>Designer</span>
            </div>
        </header>

        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident repellat culpa cum odit totam, nostrum quas omnis, eaque eos vel unde vitae tenetur laboriosam quibusdam accusantium facere. Placeat, maiores fugiat!</p>
        <footer>
            <p>Preço/hora
               <strong>R$ 40,00</strong> 
            </p>
            <button type="button">
                <img src={whatsappIcon} alt="" />
                Entrar em contato
            </button>
        </footer>
</div>
    )
}

export default FreelaItem;
